version: "3.3"

services:
  bdd:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./bdd/:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.6
    depends_on:
      - bdd
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
    environment:
      - DB_SERVER=bdd
      - DB_PREFIX=ps16_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_DOMAIN=${PS_DOMAIN}:8080
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
